# NumPy Exercise

## Import

In [2]:
# Import numpy as np
import numpy as np

## Simple Initializations

In [4]:
noten = [1, 2, 3, 4, 5, 6]
# Create a NumPy vector from the list
noten_as_vector = np.array(noten)

In [5]:
# Now create the same vector using np.arange
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [7]:
# Now create the same vector using np.linspace
np.linspace(1, 6, 6)

array([1., 2., 3., 4., 5., 6.])

In [10]:
# Create an identity matrix (1 on the diagonal, 0 everywhere else) of dimension (6,6)
einheitsmatrix = np.eye(6,6)
# Display the identity matrix
print(einheitsmatrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [11]:
# Now create a matrix with 1,2,...,6 on the diagonal and 0 everywhere else by multiplying the identity matrix by the vector of grades.
einheitsmatrix * noten

array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 6.]])

## Random Numbers and Simple Operations

In [ ]:
# Initialisiere eine Zufallszahlengenerator mit np.random.default_rng()
zufallszahlengenerator =  np.random.default_rng()


In [16]:
# Create a 6x6 matrix of normally distributed values with mean 2.5 and variance 1
normalmatrix = zufallszahlengenerator.normal(2.5, 2, (6,6))
print(normalmatrix)

[[-1.3039024   2.50980685  2.33246813  3.99902598  5.6763469   0.40504878]
 [ 3.4860015  -0.39550172  3.7485764   3.44680994  2.23258314  1.41745698]
 [-0.72904811  4.8349993   5.7016118  -2.17527762  5.26903784  2.88529045]
 [ 3.84383992  4.65938939  6.14326728  3.17871095  1.30081294  0.19693054]
 [ 5.89501237  3.19392031  3.04827936  0.69635245  3.93599965  1.71493758]
 [ 3.34551799  2.54869148  1.83685982  3.62210049  6.05018422  2.27957831]]


In [ ]:
# Now multiply the matrix by the exponential function. The resulting random variables will then follow a log-normal distribution.
np.exp(normalmatrix)

array([[2.71470337e-01, 1.23025536e+01, 1.03033402e+01, 5.45449962e+01,
        2.91881210e+02, 1.49937563e+00],
       [3.26551149e+01, 6.73342128e-01, 4.24605919e+01, 3.14000641e+01,
        9.32391999e+00, 4.12661304e+00],
       [4.82367933e-01, 1.25838495e+02, 2.99349503e+02, 1.13576618e-01,
        1.94228993e+02, 1.79087684e+01],
       [4.67044720e+01, 1.05571599e+02, 4.65572244e+02, 2.40157760e+01,
        3.67228081e+00, 1.21765946e+00],
       [3.63221329e+02, 2.43838324e+01, 2.10790438e+01, 2.00642083e+00,
        5.12133199e+01, 5.55632869e+00],
       [2.83752700e+01, 1.27903564e+01, 6.27679699e+00, 3.74160775e+01,
        4.24191166e+02, 9.77255856e+00]])

In [20]:
# Display row 6 and columns 2-3 of normalmatrix
print(normalmatrix[5, 1:3])

[2.54869148 1.83685982]


## And finally, here's a slightly more challenging task

In [24]:
# Display all entries of normalmatrix that are above the empirical mean of all observations
normalmatrix_larger = normalmatrix[normalmatrix>np.mean(normalmatrix)]
print(normalmatrix_larger)

[3.99902598 5.6763469  3.4860015  3.7485764  3.44680994 4.8349993
 5.7016118  5.26903784 2.88529045 3.84383992 4.65938939 6.14326728
 3.17871095 5.89501237 3.19392031 3.04827936 3.93599965 3.34551799
 3.62210049 6.05018422]
4.298196101292535
3.8899197857477077


In [ ]:
# Now calculate the mean and median of the previously selected elements
print(np.mean(normalmatrix_larger))
print(np.median(normalmatrix_larger))